### PR TITLE
migration of build artifacts to internal services account

### PR DESCRIPTION
**Pull request by brianwthomas**
Updating cesium-omniverse to use new bucket on internal services account

DO NOT MERGE YET UNTIL WE HAVE THE GitHub IAM user updated for permissions or this will fail.

see: https://github.com/CesiumGS/aws/issues/202

### CODE REVIEW

**Comment by brianwthomas** [comment]
leaving linting changes in so they are more inline with the other yml files we have.

**Comment by lilleyse** [comment]
Thanks @brianwthomas, I'm going to mark as draft for now but you can change it back once it's ready to merge.

I updated the yaml formatting in the VSCode workspace so that it saves with double quotes automatically now: https://github.com/CesiumGS/cesium-omniverse/pull/469/commits/c5f94bc80e99194f731144ba83636a0c157341fc

**Comment by brianwthomas** [comment]
@lilleyse, are you OK if we migrate the AWS creds on Github to reflect the new account/bucket now for this branch?  Once I test this on this branch and we see the artifacts in the InternalServices cesium-builds bucket. I'll have  @mramato update the creds for all branches and we can merge this PR.

Is that an OK plan for you?

**Comment by lilleyse** [comment]
@brianwthomas yes, that sounds good. Mark the PR as ready once CI passes and I'll merge.

**Comment by brianwthomas** [comment]
@lilleyse just wanted to update that the build succeeded and we are good to merge this

image

**Comment by brianwthomas** [comment]
Have set this ready for review, @lilleyse please merge this when you can (if you've already reviewed it)

**Review by lilleyse — APPROVED** [review]

**Comment by brianwthomas** [comment]
@mramato this has been merged. Thanks @lilleyse

**Pull request merged**
