### PR TITLE
Implemented the search field in the asset window

### LINKED ISSUE #245: Implement search bar in Cesium Assets panel
Add a search bar to the Cesium Assets panel to filter results, similar to Unity and Unreal.

image

### PR DESCRIPTION
**Pull request by weegeekps**
Resolves #245.

Implemented the search field. Wasn't happy with the styling I originally came up with for it but after some tweaking I think I've settled on something that should be good enough for most users. Does a pretty basic substring filter looking for the exact sequence of characters in the name field. This is similar to what we do for Unity and Unreal, but we may want to consider doing a more powerful indexed search in the future.

https://user-images.githubusercontent.com/284269/228000428-5c36f351-e16d-4594-b291-d27c66f812fc.mp4

### CODE REVIEW

**Comment by lilleyse** [comment]
The code looks good. I have a couple small nitpicks that don't need to hold up the PR.

* The search box seems a bit too big and the text isn't vertically centered
* The search bar vertical size increases slightly when you enter text (would it help if there were an .svg close icon?)
* The asset menu table sometimes flickers when a new filter is set

search

**Comment by weegeekps** [comment]
> The code looks good. I have a couple small nitpicks that don't need to hold up the PR.

Don't approve it yet then, I want to see what I can do to fix some of these. Unfortunately the UI system leaves a lot to be desired for centering so I don't think I can fix that, but I do notice the vertical size increasing which I missed before.

**Comment by lilleyse** [comment]
The close icon seems to be missing now.

image

**Comment by lilleyse** [comment]
Also it might be a bit late to suggest this, but did you see if it was possible to use the search widget in the content panel? I wasn't sure if they made that widget available for use outside that panel.

image

**Comment by weegeekps** [comment]
> Also it might be a bit late to suggest this, but did you see if it was possible to use the search widget in the content panel? I wasn't sure if they made that widget available for use outside that panel.

I looked at that when I was starting out. It's not possible.

**Comment by weegeekps** [comment]
@lilleyse, this is ready for a final review pass.

**Pull request merged**
