### PR TITLE
Wait for loading tiles when using the movie capture tool

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes https://github.com/CesiumGS/cesium-omniverse/issues/198.

I confirmed that `updateViewOffline` is called when the movie capture tool is active, and `updateView` is called otherwise, but I haven't been able to verify the results because I'm having trouble with the [Capturing Images and Video](https://cesium.com/learn/omniverse/omniverse-capturing-images/) tutorial. Marking as draft until that's resolved.

### CODE REVIEW

**Comment by r-veenstra** [comment]
Looks good.  Both these are with settle latency at 0


**0.17.0:**

https://github.com/CesiumGS/cesium-omniverse/assets/123468416/01fccd05-b5c6-43ec-a304-4e8db3ef3dd7

**This branch:**

https://github.com/CesiumGS/cesium-omniverse/assets/123468416/7e8997e9-f17d-4c79-9b0d-ebe90996b0e8

Captures are much faster than when using an arbitary value for settle latency too!

**Comment by lilleyse** [comment]
Great, I'll mark this as ready for review then

**Comment by corybarr** [comment]
Is the changing geometry in the render from this branch due to geometric error?

**Review by corybarr — APPROVED** [review]

**Comment by lilleyse** [comment]
> Is the changing geometry in the render from this branch due to geometric error?

I believe so

**Pull request merged**
